version: '3.8'

services:
  agent:
    build: 
      context: .
      dockerfile: docker/agent/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=src/server.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - tools

  tools:
    build:
      context: .
      dockerfile: docker/tools/Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - agent 