version: '3.8'

services:
  unified:
    build: 
      context: .
      dockerfile: docker/unified/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=src/server.py
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - unified